services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_APP=./src/app.py
      - FLASK_ENV=development
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - ./:/code
    working_dir: /code
    command: flask run --host=0.0.0.0

  worker:
    build: .
    command: celery -A src.celery_worker.celery worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - ./:/code
    working_dir: /code

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/locustfile.py
    command: -f /locustfile.py --host=http://web:5000