version: '3.8'
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ../locustfile.py:/locustfile.py
    command: -f /locustfile.py --host=http://web:5000